export enum OptionType {
    ShowOptions = 'ShowOption',
    InlineStyle = 'InlineStyle',
    InlineTemplate = 'InlineTemplate',
    ViewEncapsulation = 'ViewEncapsulation',
    ChangeDetection = 'ChangeDetection',
    Prefix = 'Prefix',
    Styleext = 'Styleext',
    Spec = 'Spec',
    Flat = 'Flat',
    SkipImport = 'SkipImport',
    Selector = 'Selector',
    Module = 'Module',
    Export = 'Export',
    Routing = 'Routing',
    RoutingScope = 'RoutingScope',
    CommonModule = 'CommonModule',
}
